### ISSUE TITLE
Update Installing Thunderbird on Linux

### ISSUE THREAD

**Issue by rtanglao** [thunderbird/knowledgebase-issues#20]
* WIP: google doc: [Public Document: SUMO KB: Installing Thunderbird on Linux](https://docs.google.com/document/d/1d7hJwbDCQs-J6GRIXE-6X0d4BFcs4fkBUi9UHgF9Htk/edit) based on [Marcelo Ghelman's revision 264172](https://support.mozilla.org/en-US/kb/installing-thunderbird-linux/history) (thanks Marcelo!)
* Current SUMO article: [Installing Thunderbird on Linux](https://support.mozilla.org/en-US/kb/installing-thunderbird-linux)

- [ ] when translating to SUMO wikimedia markup, perhaps use collapsible sections as appropriate

**Comment by hellsworth** [comment]
I did a first pass but it needs some more love for sure. I think we should have instructions specifically for ubuntu and fedora since I feel like those are the two most popular distros.

**Comment by dannycolin** [comment]
> I think we should have instructions specifically for ubuntu and fedora since I feel like those are the two most popular distros.

I don't have a strong opinion but I remember we tried to avoid distro specific instructions because it opened the door for unhappy contributors/users asking btw (pun intended) why X isn't there or why we didn't approved a revision to add X

**Comment by rtanglao** [comment]
* thanks all i suggest we document and/or link to existing distro docs for the popular distros (top 3? top 4?)
* And if somebody is unhappy about their popular or not so popular  distro not being documented in SUMO, we will accept edits to SUMO articles :-) ! just ping me here or in Matrix [#tb-support-crew](https://matrix.to/#/#tb-support-crew:mozilla.org) or on the [tb-support-crew topicbox mailing list](https://thunderbird.topicbox.com/groups/support-crew).

**Comment by hellsworth** [comment]
Roland beat me to it :)

Yep we're going to target Ubuntu, Fedora, and Arch and leverage existing distro docs that are up to date or create our own where they don't exist.

**Comment by rtanglao** [comment]
* TIL: Collapsible/foldout sections with plus signs work in SUMO KB, see SUMO github issue: [Allow kb articles to have "foldout" sections #1383]](https://github.com/mozilla/sumo/issues/1383)
     * example code:
```wiki
==Following subsections will have + signs to disclose==

[[UI:details_start]]

===subsection 1 specific content which will be collapsed until + is clicked===

blah blah about section 1
===subsection 2===

blah blah section 2
[[UI:details_end]]
```

**Comment by hellsworth** [comment]
Ok I think the document is done. @rtanglao I can put folding pieces in there if you really want but I think it would look fine without it. Otherwise should just everything be a folding part between [[UI:details_start]] and [[UI:details_end]]?

**Comment by hellsworth** [comment]
okey dokey the doc is ready for porting to SUMO. Thanks @dannycolin for your help in drafting the doc and @rtanglao for doing the SUMO heavy lifting :)

**Comment by rtanglao** [comment]
* finally done in https://support.mozilla.org/en-US/kb/installing-thunderbird-linux/revision/269961 <-- feedback including nits appreciated @hellsworth @dannycolin

**Comment by rtanglao** [comment]
* @hellsworth @dannycolin firefox .deb is created for Firefox 122, see [1826748](https://bugzilla.mozilla.org/show_bug.cgi?id=1826748), so maybe time to create a .deb for thunderbird?

**Comment by rtanglao** [comment]
@dannycolin as per [matrix](https://matrix.to/#/!WNyMcvLdvoaAcgpnIy:mozilla.org/$xqqeONt-g0w0XjNBufpYhVe5fGWk5Mv2-fmNpD-lKHA?via=mozilla.org&via=matrix.org&via=tchncs.de):
1. Review https://support.mozilla.org/en-US/kb/installing-thunderbird-linux/review/274992
2. Add a revision for `We should add a similar step for the system-wide install but the icon path should be `/opt/thunderbird/chrome/icons/default/\`

**Comment by rtanglao** [comment]
> @dannycolin as per [matrix](https://matrix.to/#/!WNyMcvLdvoaAcgpnIy:mozilla.org/$xqqeONt-g0w0XjNBufpYhVe5fGWk5Mv2-fmNpD-lKHA?via=mozilla.org&via=matrix.org&via=tchncs.de):
> 
>     1. Review https://support.mozilla.org/en-US/kb/installing-thunderbird-linux/review/274992
> 
>     2. Add a revision for `We should add a similar step for the system-wide install but the icon path should be `/opt/thunderbird/chrome/icons/default/`

I believe https://support.mozilla.org/en-US/kb/installing-thunderbird-linux/review/274992 fixed 2. as well so closing
