### ISSUE TITLE
Update "Upgrading from an older version of Thunderbird" for 115

### ISSUE THREAD

**Issue by rtanglao** [thunderbird/knowledgebase-issues#31]
* [Upgrading from an older version of Thunderbird](https://support.mozilla.org/kb/upgrading-older-version-thunderbird ) needs updates for 115
* As of 122 you simply can't download 122 or newer and manually do a direct upgrade
* Upgrading indirectly e.g. 60->78->91->102->115->122 or newer should work
* Directly upgrading from 91->122 or newer should work
* See https://github.com/thunderbird/thunderbird-website/pull/347
- [x] @Sancus to tell us which version to start with based on stats, let's call it `X`
- [ ] if they have IMAP then just skip the whole thing and create a new profile, e.g. if they are older than 91 but filters could be an issue (need to research on filters)
- [ ] also if they have POP set to not delete on server, then they can just switch to imap and create a new profile
- [x] install each version starting at version `X` and each subsequent ESR version and then test the upgrade steps, and add anything to the article that is missing for each version.
    - [x] create an email account
    - [x] Create addressbook entries
- [x]  link to SUMO KB articles and revise appropriately: [Thunderbird Software Update Failed](https://support.mozilla.org/en-US/kb/thunderbird-software-update-failed)  and perhaps [Updating Thunderbird](https://support.mozilla.org/en-US/kb/updating-thunderbird)
- [x] looks like installing 115 over 78 is not recommended, so get rid of the section that recommends installing current version  over 78; instead document the Help > About dance and instead replace with material from Wayne's message on Matrix which I've copied and pasted into [a comment in this github issue](https://github.com/thunderbird/knowledgebase-issues/issues/31#issuecomment-1967268390)
- [x] Ask @mkmelin about filter compatibility so for advanced users they can maybe just install current version and somehow restore their filters from pre60 versions of Thunderbird?
- [x] recorder the article i.e. most used scenarios i.e. newer version upgrade first, least used scenarios last and perhaps with least used scenarios using collapsible sections and by default least used collapsed

**Comment by rtanglao** [comment]
* 50K on 52
* 90K on 60
* 80K on both 78 and 68
* Therefore let's start from 60

**Comment by rtanglao** [comment]
* https://www.reddit.com/r/windows/comments/15qpei5/download_the_official_windows_7_iso_in_2023/

**Comment by rtanglao** [comment]
* Notes: https://github.com/thunderbird/knowledgebase-issues/wiki/Update-%22Upgrading-from-an-older-version-of-Thunderbird%22-for-115-%2331

**Comment by rtanglao** [comment]
* There was an issue with a Balrog rule that prevented an upgrade to from Windows 11 102->115 which Rob fixed yesterday

**Comment by rtanglao** [comment]
* WIP https://docs.google.com/document/d/1mr5Wx5YNYYCMiO3TvMETAPrVWF2J5BewJN1dviJbluY/edit

**Comment by rtanglao** [comment]
* @Sancus and/or @jfx2006 optional: @MelissaAutumn Please review: https://docs.google.com/document/d/1mr5Wx5YNYYCMiO3TvMETAPrVWF2J5BewJN1dviJbluY/edit

**Comment by MelissaAutumn** [comment]
Optional approval here!

**Comment by rtanglao** [comment]
* Since the numbers are so low, ([see previous comment](https://github.com/thunderbird/knowledgebase-issues/issues/31#issuecomment-1892611608)) for less than 60 i recommend not documenting it, it's hard to test as well!, @wsmwk where is the place to document this for institutional knowledge?

**Comment by rtanglao** [comment]
*  @wsmwk made another revision: https://support.mozilla.org/en-US/kb/upgrading-older-version-thunderbird/review/276950 Still not 100% happy with this. I guess i would like to come up with a better sentence about not documenting upgrades to 60.

**Comment by rtanglao** [comment]
This is what I have as an accumulation of info collected over the years,  combined with other people's knowledge...

https://www.reddit.com/r/Thunderbird/comments/rsxrpo/should_i_upgrade/

https://support.mozilla.org/en-US/questions/1361911

https://support.mozilla.org/en-US/questions/1310757#answer-1362246

The profile structure has not changed, but Thunderbird does do some "migration" actions between some versions of Thunderbird. Version XXX is too old for the update process to work, because the update servers used by version XXX are long gone. However it is possible to effect the update process by downloading and installing newer version - but you do NOT want to make a massive version jump, because certain versions actually migrate (change) Thunderbird data to proper format for the newer version.

You don't need to do any profile editing. Backup your profile. Then install and run each of the following versions for your OS and language which you will find at http://archive.mozilla.org/pub/thunderbird/releases/

### Upgrading Versions
http://archive.mozilla.org/pub/thunderbird/releases/1.5.0.14/win32/en-US/
http://archive.mozilla.org/pub/thunderbird/releases/2.0.0.24/win32/en-US/
http://archive.mozilla.org/pub/thunderbird/releases/3.0.11/win32/en-US/
http://archive.mozilla.org/pub/thunderbird/releases/3.1.20/win32/en-US/
http://archive.mozilla.org/pub/thunderbird/releases/5.0/win32/en-US/
12.0.1
(15.0.1 skip)
17.0.8
24.8.0
http://archive.mozilla.org/pub/thunderbird/releases/45.8.0/win32/en-US/
http://archive.mozilla.org/pub/thunderbird/releases/52.9.1/win32/en-US/
http://archive.mozilla.org/pub/thunderbird/releases/60.9.0/win32/en-US/
use automatic updates from there

### An example

5.0 for example http://archive.mozilla.org/pub/thunderbird/releases/5.0/win32/en-US/
12.0.1
(15.0.1 skip)
17.0.8
24.8.0
(38.0.8 skip)
45.8.0
52.9.1

Then do Help > About until you get to version 68. Stay on version 68 until you get prompted to update to version 78

**Comment by rtanglao** [comment]
* From [#Thunderbird Developers in Matrix](https://matrix.to/#/!fubIsJzeAcCcjYTQvm:mozilla.org/$74ZiJwJ10aabOG610bpFqHkIk_i6xmA6weBc-8hzy-Q?via=kewis.ch&via=mozilla.org&via=matrix.org):

@mkmelin : and other filter experts:

- RE:  filter compatibility:  For advanced users they can maybe just install current version i.e. TB 115 and somehow restore their filters from pre60 versions of Thunderbird? Or did filters change before 60 and after 60 so you need to do the manual upgrade over older versions (TB 1.5->2->3.1->5->12->17->24->45->52->60 dance so filters get upgraded to the current Supernova format?
- Context: editing SUMO KB article: [Upgrading from an older version of Thunderbird](https://support.mozilla.org/en-US/kb/upgrading-older-version-thunderbird) ;  github KB issue:  [Update "Upgrading from an older version of Thunderbird" for 115 #31](https://github.com/thunderbird/knowledgebase-issues/issues/31) )

**Comment by rtanglao** [comment]
* Magnus said in matrix there is not shortcut for filter migration
